import "./globals.css";
// import { Montserrat } from "next/font/google";

// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "My blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
